search_app/urls.py
from django.urls import path

from . import views

app_name = 'search_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('saved/', views.SavedView.as_view(), name='saved'),
]

vulners_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search_app.urls')),
]

search_app/models.py
from django.db import models

class SavedObjects(models.Model):

    object_id = models.CharField("Object_id", max_length=200, blank=False, unique=True)

    def __str__(self):
        return self.object_id

search_app/views.py
from django.shortcuts import render
from django.views import View
import requests
import urllib.parse
from .models import SavedObjects


class IndexView(View):

    @staticmethod
    def get(request):
        saved_objects = list(SavedObjects.objects.all().values_list('object_id', flat=True))

        # configuration for lucene query
        vendor_lucene_field = 'title'  # I did't find the field 'vendor' in the documentation. Therefore, I use the field 'title' as the most suitable.
        type_lucene_field = 'bulletinFamily'

        search_vendor = request.GET.get('vendor') or ''
        search_type = request.GET.get('type') or ''

        if search_vendor and search_type:
            query_string = '%s:%s AND %s:%s' % (vendor_lucene_field, search_vendor, type_lucene_field, search_type)
        elif search_vendor:
            query_string = '%s:%s' % (vendor_lucene_field, search_vendor)
        else:
            query_string = '%s:%s' % (type_lucene_field, search_type)

        query_url = urllib.parse.quote_plus(query_string)
        api_search_url = 'https://vulners.com/api/v3/search/lucene/?query={}'.format(query_url)

        elements = []
        r = requests.get(api_search_url)

        if r.status_code == 200:
            json_data = r.json()
            search_result = json_data.get('data').get('search')

            for item in search_result:
                elements.append(item.get('_source'))

        context = {
            'elements': elements,
            'saved': saved_objects,
            'query_type': search_type,
            'query_vendor': search_vendor,
        }

        return render(request, 'search_app/index.html', context=context)

    @staticmethod
    def post(request):
        """
        Saving selected items by ids
        :param request:
        :return: default view
        """
        object_ids = request.POST.getlist('object_id')
        for object_id in object_ids:
            SavedObjects.objects.update_or_create(object_id=object_id)

        return IndexView.get(request)


class SavedView(View):
    @staticmethod
    def get(request):
        elements = []
        saved_objects = SavedObjects.objects.all()

        for object_id in saved_objects:
            api_search_url = 'https://vulners.com/api/v3/search/id/?id={}'.format(object_id)
            r = requests.get(api_search_url)

            if r.status_code == 200:
                json_data = r.json()
                elements.append(json_data.get('data').get('documents').get(str(object_id)))

        context = {
            'elements': elements
        }
        return render(request, 'search_app/index.html', context=context)

    @staticmethod
    def post(request):
        """
        Removing saved items by ids
        :param request:
        :return: saved view
        """
        object_ids = request.POST.getlist('object_id')
        for object_id in object_ids:
            SavedObjects.objects.filter(object_id=object_id).delete()

        return SavedView.get(request)

search_app/templates/search_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <title>{% block title %}rwp{% endblock title %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 30px">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% url 'search_app:index' as main_page_url %}
            {% if main_page_url ==  request.get_full_path %}
                <li class="nav-item active">
            {% else %}
                <li class="nav-item">
            {% endif %}
                    <a class="nav-link" href="{{ main_page_url }}">Main page</a>
                </li>
            <li class="nav-item">
            {% url 'search_app:saved' as saved_page_url %}
            {% if saved_page_url ==  request.get_full_path %}
                <li class="nav-item active">
            {% else %}
                <li class="nav-item">
            {% endif %}
                    <a class="nav-link" href="{{ saved_page_url }}">Saved</a>
                </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="get" action="/">
            <input class="form-control mr-sm-2" name="vendor" type="search" placeholder="Vendor" aria-label="Search"
            value="{% block query_vendor %}{% endblock query_vendor %}">
            <input class="form-control mr-sm-2" name="type" type="search" placeholder="Type" aria-label="Type"
            value="{% block query_type %}{% endblock query_type %}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col">
            {% block content %}{% endblock content %}
        </div>
    </div>
</div>
</body>
</html>

search_app/templates/search_app/index.html
{% extends 'search_app/base.html' %}
{% block title %}Vulners - Search{% endblock title %}
{% block query_vendor %}{{ query_vendor }}{% endblock query_vendor %}
{% block query_type %}{{ query_type }}{% endblock query_type %}

{% block content %}
    <form action="{{ request.get_full_path }}" method="post">
        {% if elements %}
            <div>
                {% for element in elements %}
                    <div class="card" style="margin-bottom: 20px">
                        <div class="card-body">
                            {% if element.id in saved %}
                                <div class="alert alert-success" role="alert">
                                    You saved this item to your save-list
                                </div>
                            {% else %}
                                <input name="object_id" type="checkbox" style="transform: scale(1.5);"
                                       value="{{ element.id }}">
                            {% endif %}
                            <h5 class="card-title">{{ element.title }}</h5>
                            <p class="card-text">Type: {{ element.bulletinFamily }}</p>
                        </div>
                        <div class="card-footer text-muted">
                            {{ element.description }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>Nothing fond.</p>
        {% endif %}
        <nav class="navbar fixed-bottom navbar-light bg-dark">
            {% url 'search_app:saved' as saved_page_url %}
            {% if saved_page_url ==  request.get_full_path %}
                <button class="btn btn-danger" type="submit">Delete</button>
            {% else %}
                <button class="btn btn-primary" type="submit">Save</button>
            {% endif %}
        </nav>
        {% csrf_token %}
    </form>
{% endblock content %}